instance_groups:
  prod:
    provider: aws
    size: t3.micro
    ami: ami-0c02fb55956c7d316
    name_pattern: "test-aws-{number}"
    quantity: 1
    cleanup: true
  dev:
    provider: azure
    size: Standard_B1s
    image: UbuntuServer
    name_pattern: "test-azure-{number}"
    quantity: 1
# Enable cleanup in CI to remove test Azure VMs after run
    cleanup: true
# Final test comment - trigger CI again
# CI trigger timestamp: 2025-09-22T00:52:00Z
# Additional pipeline trigger comment: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# CI trigger 2025-09-23T01:05:29Z
