instance_groups:
  prod:
    provider: aws
    size: t3.micro
    ami: ami-0c02fb55956c7d316
    name_pattern: "test-aws-{number}"
    quantity: 1
    cleanup: true
  dev:
    provider: azure
    size: Standard_B1s
    image: Ubuntu2204
    name_pattern: "test-azure-{number}"
    quantity: 1
    cleanup: false
# Final test comment - trigger CI again
# CI trigger timestamp: 2025-09-22T00:52:00Z
